modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "dclink_neoforge"
version = "${version}"
displayName = "DCLink"
description = '''My Description'''

[[mixins]]
config = "dclink-neoforge.mixins.json"
